### ISSUE TITLE
Do we need a monorepo?

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/data-modules#16]
@soltanireza65 suggested we make this repo a Lerna monorepo, for two reasons:
1) it adds value but we don't need to use it consistently
2) I'm working with 2 packages: soukai-solid-utils and data-modules which has a direct dependency on it. I don't want soukai-solid-utils to be built and published each and every time.

**Comment by michielbdejong** [comment]
Let's use https://github.com/pondersource/soukai-solid-utils for ths soukai-solid-utils package and maintain that separately from data-modules.

**Comment by michielbdejong** [comment]
Even though it's clear that in @soltanireza65's work flow there is a strong interdependency between features and bug fixes in the Bookmarks data module and in Soukai[-utils] this doesn't mean they are part of the same project. We also don't want to put rdflib and LDO and inrupt-solid-client all in a monorepo together, we want the ecosystem of libs that are available to Solid app devs to be as open and modular as possible.

Whereas I understand that a monorepo would make your dev setup easier, I also think it would make other people's dev setup harder. As an example of this, if I want to write an app that uses Soukai to fetch the type index, I would benefit from being able to use your latest code, but for now I can't, _precisely_ because you weren't forced to push each feature and bugfix in soukai-solid-utils to npm, or to write issues, PRs and tests for each feature that are independent from how you use it in the bookmarks data module.

I therefore propose you use https://docs.npmjs.com/cli/v8/commands/npm-link instead of Lerna, and we keep this repo as we had it.

**Comment by angelo-v** [comment]
My understanding of using this as a monorepo was that we keep all the data modules (contacts, bookmarks, chat etc.) in here, but not necessarily other projects that the data modules depend upon
