### ISSUE TITLE
Milestones list

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/data-modules#30]
Within Ponder Source we're establishing a coop between Yashar, Mahdi, Reza and Erfan. I propose to split the 50k of this project 50/50 between this coop on the one hand, and Angelo / Jackson / Rosano on the other hand, this works out pretty nicely.
With what we have started already we could plan roughly: (3+3+3+2+5+.3+.5+3.2+5)+(9+9+7) = 50k
* #6 3k
* #31 3k
* #7 3k
* #8 2k
* Pivot 5k? (coordinate with Jan and Theo who have their own NLnet grant)
* solidcommunity.net NSS->CSS migration (Mahdi) 0k3?
* solidcommunity.net server admin (Mahdi) 0k5?
* Solid Data Modules for Android 3k2
* Solid backend for rs.js (Yashar) 5k?
* Addressbook module, rdflib-based modules, etc (Angelo) 9k?
* Chat module, automated code generation, LDO-based modules, etc (Jackson) 9k?
* Outreach to app devs etc (Rosano) 7k

I don't remember exactly which amounts we said last time we discussed this, I remember we had a rough list in HackMD at some point but can't find it now. See also https://github.com/solid-contrib/data-modules/blob/main/days-worked.md.
But we can shift resources back and forth depending on who works when. Let's discuss in the meeting on Friday!

**Comment by michielbdejong** [comment]
For Android:
1) Android-compatible Java library
2) Solid services app (GUI to authenticate) - could be used as a hello-world app
3) Create the SDK for other app developers

**Comment by michielbdejong** [comment]
Hey Michiel,

Here's my statement of work based on what we discussed:

Solid-Data-Modules upgrades using LDO:

Auto-generated Data Model (€13,000)
• Add feature to @ldo/solid to suggest new URIs based on the type index. This must be documented on [ldo.js.org](http://ldo.js.org/) and published to NPM. (€2,000)
• Add feature to @ldo/solid to iterate through everything of a certain type in the type index. This must be documented on [ldo.js.org](http://ldo.js.org/) and published to NPM. (€2,000)
• Add hook(s) for type-index support in @ldo/solid-react. This must be documented on [ldo.js.org](http://ldo.js.org/) and published to NPM. (€1,000)
• Add a new command to @ldo/cli to generate an NPM project that can be published to NPM. This command must be documented on [ldo.js.org](http://ldo.js.org/) and published to NPM (€2,000)
• Add support for common ShEx use cases (Or Type, And Type, Different Cardinalities on identical field in different shapes). This task will require a refactor of the @ldo/type-traverser, @ldo/schema-converter-shex, but it will allow for many more kinds of ShEx shapes to be parsed. (€6,000)

Solid Chat Module (€7,000)
• Add support for Webhooks in @ldo/solid (€3,000)
• Make a module for chat based on items generated from LDO. The module backwards compatible with old versions of chat while being updated to implement a “follow your nose” infrastructure. This module must be documented and released to NPM. (€4,000)

**Comment by michielbdejong** [comment]
Let's scrap Pivot and then give Jackson:
* 4k for the chat module
* 5k for code generation
* 5k for LDO improvement work

**Comment by michielbdejong** [comment]
@rosano and @angelo-v as discussed, please each chop up your milestone into 3 smaller chunks, so they're easier to claim and you don't have to wait so long for completion and getting paid for each chunk of work

**Comment by michielbdejong** [comment]
@angelo-v I chopped your milestones into M2, P2, P3, see https://github.com/solid-contrib/data-modules/blob/main/admin/milestones.md. I was going to do P2 myself but moved it to you to keep you at 10k.

@jaxoncreed as discussed, you now have 14k worth of milestones assigned, divided over M3, P4, F1, F3.

@erfangholami and @rosano please each create a PR to this file to update the 'first', 'second', 'last' part of your plan for Android and outreach, respectively.

**Comment by angelo-v** [comment]
We need to discuss what's in the scope of a module then. My plan was to chop down the contacts module into smaller parts. I don't think I can finish all other modules as well in that budget

**Comment by michielbdejong** [comment]
@angelo-v OK so let's drop the remotestorage.js modules then, and you just keep the small task of making all 4 data modules work well in combination with rdflib.js when they already work with an authenticated fetcher. That shouldn't be too hard I think, for instance if you have a vanilla data module that exposes `async getAllAddressbooks()` which fetches and returns them, then when you add rdflib as a local triple store you can just split that into two methods, `async fetchAllAddressbooks()` which fetches them and stores them in a local rdflib triple store  + `getAllAddressbooks()` which then synchronously queries that local in-memory triple store.
Let's make that 3k and then you get 6k for Contacts data module parts 1/2/3
