### ISSUE TITLE
Guide new developer to pick framework

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/data-modules#39]
As a new developer, if I land on https://github.com/solid-contrib/data-modules/tree/main/bookmarks I have no idea which one I should pick.

**Comment by michielbdejong** [comment]
Also, the list of options doesn't match the list of folders available :)

**Comment by soltanireza65** [comment]
@michielbdejong 
https://github.com/solid-contrib/data-modules/blob/3a1c9a7f712166bb79f8afea586de01a2ff1b67c/bookmarks/README.md
