### ISSUE TITLE
Vanilla bookmarks docs is aimed at people who already know a bit about Solid

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/data-modules#40]
Because https://github.com/solid-contrib/data-modules/tree/main/bookmarks/vanilla starts by talking about typeIndex, and that's not a good DX for a full-stack developer who meets Solid for the first time.

**Comment by soltanireza65** [comment]
moved typeIndex docs to end.
so newcomers will first see how to use the module itself, without the need to know what a TypeIndex is.
