### ISSUE TITLE
Bookmarks from Poddit not showing up

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/data-modules#76]
I have one bookmark in Poddit:
![Screenshot 2024-01-22 at 16 01 26](https://github.com/solid-contrib/data-modules/assets/408412/4c77b271-2990-40d2-a638-57232bda05c1)

but it's not showing up in the list when I do `await Bookmark.getAll(fetcher, webId)`:
<img width="1619" alt="Screenshot 2024-01-22 at 16 02 24" src="https://github.com/solid-contrib/data-modules/assets/408412/0c60a3a9-906f-4803-987e-af26bd9f61bc">

**Comment by michielbdejong** [comment]
Fixing for Poddit will probably also fix for Markbook since I see the same one there:

<img width="1465" alt="Screenshot 2024-01-22 at 16 48 48" src="https://github.com/solid-contrib/data-modules/assets/408412/42e97f26-07c2-4653-be74-b15f821a452c">

**Comment by soltanireza65** [comment]
I have to see the predicates used in Poddit, could you please provide the GitHub repo for Poddit??

**Comment by michielbdejong** [comment]
It's on GitLab: https://gitlab.com/vincenttunru/poddit/-/tree/master

**Comment by michielbdejong** [comment]
@soltanireza65 I'll take this one

**Comment by soltanireza65** [comment]
> @soltanireza65 I'll take this one

Hint: maybe just update internal mapper methods
